export const TabNames = {
    BACK_TAB: 'BACK_TAB',
    CLUSTER_ANALYSIS: 'CLUSTER_ANALYSIS',
    SCATTER_PLOT: 'SCATTER_PLOT',
    DISTANCE_MEASURES: 'DISTANCE_MEASURES',
    RD_SPLITS: 'RD_SPLITS'
}
